### ISSUE TITLE
issues changing kits

### ISSUE THREAD

**Issue by slvlr** [slvlr/TerrorPVP#45]
(There are 2 issues listed in this)

1)
In safezone you can change kits when you have a kit selected. This is fine though if you leave safezone and type a kitname outside the safezone while running at the safezone border sometimes you are able to select a different kit and change kits while in the warzone.
fix: Either disable changing kits entirely when you have one selected or put a check to see if they have left the safezone in this life? 

2)
If a player disconnects in the warzone, when they reconnect they will be in the same location and their kit will change to swordsman. 
fix:  they should respawn in the safezone without a kit.  
if they were in combat it will count as a death and points will be lost.
if they weren't in combat they will just respawn without any losses.

**Comment by DebugingLonks** [comment]
For "2" 

The disconnect bug happens when the plugin is not working right. This happens at random points and I have no idea why. There are three ways to tell if the plugin is not working right.
1: Thor won't work at all.
2: When you kill someone, you get no points. You don't loose any either.
3: When you die from a player you drop all your stuff. Also your weapon when killing someone will have the lore from factions "(Name) killed (Name)!"

"Fix: they should respawn in the safezone without a kit" This happens usualy, that's the bug.
"If they were in combat" Combat logging is another bug report lol I think you fixed that tho.
"If they weren't in combat" that was what was meant to happen.

**Comment by slvlr** [comment]
2.
if they were in combat it will count as a death and points will be lost.


This works though there is not a message on screen displayed to the killer. could you add this please?
Everything else works fine.

**Comment by DebugingLonks** [comment]
I think "2" has been fixed, as this rarely happens, and it has not happens recently.

**Comment by DebugingLonks** [comment]
Whole bug has been fixed. If its not, this is due to combat tagging.
